# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SlopeIndentifier
                                 A QGIS plugin
 This plugin removes border effect on DOD of cliff top boulders (CTD)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-22
        copyright            : (C) 2023 by LETG, IUEM (Plouzané, FR)
        email                : antoineledoeuff@yahoo.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'LETG, IUEM (Plouzané, FR)'
__date__ = '2023-05-22'
__copyright__ = '(C) 2023 by LETG, IUEM (Plouzané, FR)'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterString,
                       QgsRasterLayer)
from qgis.analysis import (QgsRasterCalculator,
                           QgsRasterCalculatorEntry)
import processing
import os
import re
import geopandas as gpd


class SlopeIndentifierAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    INPUT = 'INPUT'
    CURRENT_YEAR = 'CURRENT_YEAR'
    LAST_YEAR = 'LAST_YEAR'
    OUTPUT_DOD = 'OUTPUT_DOD'

    def initAlgorithm(self, config):

        # INPUT
        self.addParameter(
            QgsProcessingParameterFile(
                self.INPUT,
                self.tr('Dossier contenant les DOD (rangés par dossier de site)'),
                behavior=QgsProcessingParameterFile.Folder,
                fileFilter='Tous les fichiers (*.*)'
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.CURRENT_YEAR,
                'Année x',
                '2022'
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.LAST_YEAR,
                'Année x-1 ans',
                '2021'
            )
        )

        # OUTPUT
        self.addParameter(
            QgsProcessingParameterFile(
                self.OUTPUT_DOD,
                self.tr('Dossier contenant les DOD nettoyés (rangés par dossier de site)'),
                behavior=QgsProcessingParameterFile.Folder,
                fileFilter='Tous les fichiers (*.*)',
                defaultValue=None
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.

        dir_dod = self.parameterAsFile(parameters, self.INPUT, context)
        current_year = self.parameterAsString(parameters, self.CURRENT_YEAR, context)
        last_year = self.parameterAsString(parameters, self.LAST_YEAR, context)
        dir_dod_cleaned = self.parameterAsFile(parameters, self.OUTPUT_DOD, context)

        # Iterate over the DODs
        for root, dirs, files in os.walk(dir_dod):
            for file in files:

                """
                For process just one site, us this if statement:
                
                if file.endswith('.tif') and re.search(rf'NameOfSite_{current_year}_{last_year}',file):
                """

                if re.search(rf'{last_year}_{current_year}_bowl_cleaned.tif', file):
                    feedback.pushInfo(f"Processing {file}")
                    place = re.match(r'(^.*?(?=_))', file)
                    place = place.group(1)

                    # Subdirectory containing intermediate layer
                    dir_detail = f"{dir_dod_cleaned}/{place}/SLOPE_DETAILS"
                    # Create it if it doesn't already exists
                    if not os.path.exists(dir_detail):
                        os.makedirs(dir_detail)

                    # -----------------------------------------
                    # COMPUTE SLOPE PARAMETERS
                    # -----------------------------------------

                    feedback.pushInfo(f"Computing slope for {file}")

                    dod_path = f'{dir_dod}/{place}/{file}'
                    slope_path = f'{dir_detail}/{place}_{last_year}_{current_year}_DOD_slope.tif'
                    dx_path = f'{dir_detail}/{place}_{last_year}_{current_year}_DOD_slope_dx.tif'
                    dy_path = f'{dir_detail}/{place}_{last_year}_{current_year}_DOD_slope_dy.tif'
                    dxx_path = f'{dir_detail}/{place}_{last_year}_{current_year}_DOD_slope_dxx.tif'
                    dyy_path = f'{dir_detail}/{place}_{last_year}_{current_year}_DOD_slope_dyy.tif'
                    dxy_path = f'{dir_detail}/{place}_{last_year}_{current_year}_DOD_slope_dxy.tif'

                    if os.path.exists(slope_path):
                        feedback.pushInfo("Slopes parameters already computed")
                    else:
                        feedback.pushInfo(f"Computing slopes")
                        params = {
                            'elevation': dod_path,
                            'format': 0,
                            'precision': 0,
                            '-a': True,
                            '-e': True,
                            '-n': False,
                            'zscale': 1,
                            'min_slope': 0,
                            'slope': slope_path,
                            'dx': dx_path,
                            'dy': dy_path,
                            'dxx': dxx_path,
                            'dyy': dyy_path,
                            'dxy': dxy_path,
                            'GRASS_REGION_PARAMETER': None,
                            'GRASS_REGION_CELLSIZE_PARAMETER': 0,
                            'GRASS_RASTER_FORMAT_OPT': '',
                            'GRASS_RASTER_FORMAT_META': ''
                        }

                        processing.run(
                            "grass7:r.slope.aspect",
                            params,
                            context=context,
                            feedback=feedback
                        )

                        feedback.pushInfo(f"Compute of slopes done")

                    # -----------------------------------------
                    # CREATE MASK LAYER
                    # -----------------------------------------

                    slope_mask = f'{dir_detail}/{place}_{last_year}_{current_year}_DOD_slope_mask.tif'

                    if os.path.exists(slope_mask):
                        feedback.pushInfo('Raster mask already generated')
                    else:
                        feedback.pushInfo('Creating raster mask layer')

                        layers = [
                            QgsRasterLayer(slope_path),
                            QgsRasterLayer(dx_path),
                            QgsRasterLayer(dy_path),
                            QgsRasterLayer(dxx_path),
                            QgsRasterLayer(dyy_path),
                            QgsRasterLayer(dxy_path)
                        ]

                        # Paramètre de la calculatrice raster
                        entries = []

                        for idx, layer in enumerate(layers):
                            entry = QgsRasterCalculatorEntry()
                            entry.ref = f'ras{idx}@1'
                            entry.raster = layer
                            entry.bandNumber = 1
                            entries.append(entry)

                        calc = QgsRasterCalculator(
                            "(abs('ras0@1')>=77) OR (abs('ras1@1')>=5) OR (abs('ras2@1')>=5) OR (abs('ras3@1')>=150) OR (abs('ras4@1')>=150) OR (abs('ras5@1')>=40)",
                            # Expression
                            slope_mask,  # Output
                            'GTiff',  # Format
                            layers[1].extent(), layers[1].width(), layers[1].height(),  # Extents
                            entries  # Les rasters en entrées
                        )
                        calc.processCalculation()

                        feedback.pushInfo("Raster mask layer generated")

                    # POLYGONIZE

                    slope_mask_pol = f'{dir_detail}/{place}_{last_year}_{current_year}_DOD_slope_mask.shp'

                    if os.path.exists(slope_mask_pol):
                        feedback.pushInfo('Shapefile mask already exists')
                    else:
                        feedback.pushInfo("Polygonizing")
                        params = {
                            'INPUT': slope_mask,
                            'BAND': 1,
                            'FIELD': 'DN',
                            'EIGHT_CONNECTEDNESS': False,
                            'EXTRA': '',
                            'OUTPUT': slope_mask_pol
                        }

                        processing.run(
                            "gdal:polygonize",
                            params,
                            context=context,
                            feedback=feedback
                        )

                        feedback.pushInfo("Polygonize done")

                        # Conserve only slopes

                        feedback.pushInfo('Filtering vectorial mask')

                        mask_shp = gpd.read_file(slope_mask_pol)
                        mask_shp = mask_shp.loc[mask_shp.DN == 0]
                        mask_shp.to_file(slope_mask_pol, driver="ESRI Shapefile")

                        feedback.pushInfo('Filtering vectorial mask done')

                    # -----------------------------------------
                    # CLIP DOD BY MASK
                    # -----------------------------------------

                    dod_cleaned = f"{dir_dod_cleaned}/{place}/{place}_{last_year}_{current_year}_DOD_be_cleaned.tif"

                    if os.path.exists(dod_cleaned):
                        feedback.pushInfo("Raster already clipped")
                    else:
                        feedback.pushInfo("Clipping DOD by mask")

                        params = {
                            'INPUT': dod_path,
                            'MASK': slope_mask_pol,
                            'SOURCE_CRS': None,
                            'TARGET_CRS': None,
                            'TARGET_EXTENT': None,
                            'NODATA': None,
                            'ALPHA_BAND': False,
                            'CROP_TO_CUTLINE': True,
                            'KEEP_RESOLUTION': False,
                            'SET_RESOLUTION': False,
                            'X_RESOLUTION': None,
                            'Y_RESOLUTION': None,
                            'MULTITHREADING': False,
                            'OPTIONS': '',
                            'DATA_TYPE': 0,
                            'EXTRA': '',
                            'OUTPUT': dod_cleaned
                        }

                        processing.run(
                            "gdal:cliprasterbymasklayer",
                            params,
                            context=context,
                            feedback=feedback
                        )

                        feedback.pushInfo("Clip done with success")

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Remove border effect'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'DOD processing'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SlopeIndentifierAlgorithm()
